steps:
- name: gcr.io/cloud-builders/git
  args: ['clone', 'https://github.com/Zerneax/myCity']
- name: 'gcr.io/$PROJECT_ID/npm'
  args: ['install']
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'test:unit']
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy']
timeout: '1600s'
