steps:
- name: 'grc.io/cloud-builders/npm'
  args: ['install']
- name: 'grc.io/cloud-builders/npm'
  args: ['run', 'test:unit']
- name: 'grc.io/cloud-builders/npm'
  args: ['run', 'build']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy']
timeout: '1600s'
